application: mywebapp-123
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /firebase-messaging-sw\.js
  static_files: firebase-messaging-sw.js
  upload: firebase-messaging-sw\.js

- url: /manifest\.json
  static_files: manifest.json
  upload: manifest\.json

- url: /icons
  static_dir: icons

- url: /scripts
  static_dir: scripts

- url: /views
  static_dir: templates/views

- url: /styles
  static_dir: templates/styles

- url: /loginpage\.html
  static_files: loginpage.html
  upload: loginpage\.html

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
